name: Deploy ReactJS on Nginx

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "19.8.1"
    - run: npm install
    - run: npm run build
    - run: cp -r ./build /home/leekyusung/nginx-root/nomad-react-for-beginners
